version: "1.29.2"
services:
  frontend:
    image: 654654542135.dkr.ecr.eu-central-1.amazonaws.com/mein-frontend:latest
    environment:
      - VIRTUAL_HOST=frontend.local

  backend:
    image: 654654542135.dkr.ecr.eu-central-1.amazonaws.com/mein-backend:latest
    environment:
      - ENV=production 
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dishlist
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=|]{>#k3siGE}}o9kyCtY2t]9MdvC
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - CONFIG_PATH=/config
    volumes:
      - ./backend/config:/config
      
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=|]{>#k3siGE}}o9kyCtY2t]9MdvC
      - MYSQL_DATABASE=dishlist
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=|]{>#k3siGE}}o9kyCtY2t]9MdvC
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db_data:
  web_root:
